/**
 * Generated by tsnapi — public API snapshot of `valtio-sync/client`
 */
// #region Types
export type AcceptedSyncOp = {
  mutationId: string;
  collection: string;
  id: string;
  serverVersion: number;
  record?: JsonRecord;
};
export type CollectionChanges = {
  upserted: Array<{
    id: string;
    serverVersion: number;
    record: JsonRecord;
  }>;
  deleted: Array<{
    id: string;
    serverVersion: number;
  }>;
};
export type CreateSyncOp = {
  mutationId: string;
  collection: string;
  type: 'create';
  id: string;
  value: JsonRecord;
  touched: string[];
};
export type DeleteSyncOp = {
  mutationId: string;
  collection: string;
  type: 'delete';
  id: string;
  baseServerVersion: number | null;
};
export type JsonRecord = Record<string, JsonValue>;
export type JsonValue = string | number | boolean | null | JsonValue[] | {
  [key: string]: JsonValue;
};
export type RejectedSyncOp = {
  mutationId: string;
  collection: string;
  id: string;
  reason: SyncRejectionReason;
  message?: string;
  serverRecord?: JsonRecord;
  serverVersion?: number;
};
export type SyncError = {
  reason: SyncRejectionReason | 'network' | 'auth';
  message?: string;
};
export type SyncOp = CreateSyncOp | UpdateSyncOp | DeleteSyncOp;
export type SyncRejectionReason = 'validation' | 'forbidden' | 'conflict' | 'not_found' | 'server_error';
export type SyncRequest = {
  clientId: string;
  schemaVersion: number;
  lastServerSeq: number | null;
  ops: SyncOp[];
};
export type SyncResponse = {
  serverSeq: number;
  accepted: AcceptedSyncOp[];
  rejected: RejectedSyncOp[];
  changes: Record<string, CollectionChanges>;
};
export type UpdateSyncOp = {
  mutationId: string;
  collection: string;
  type: 'update';
  id: string;
  patch: JsonRecord;
  touched: string[];
  baseServerVersion: number | null;
};
// #endregion

// #region Functions
export declare function valtioSync(): never;
// #endregion

// #region Other
export { AccountDefinition }
export { CollectionDefinition }
export { FieldMap }
export { infer }
export { InferFields }
export { SyncSchema }
// #endregion