/**
 * Generated by tsnapi — public API snapshot of `valtio-sync/drizzle`
 */
// #region Types
export type ApplyOpsWithDrizzleOptions<TContext, TTransaction extends DrizzleLikeTransaction = DrizzleLikeTransaction> = {
  db: DrizzleLikeDatabase<TTransaction>;
  syncEvents: DrizzleSyncEventConfig<TContext, TTransaction>;
  handlers: Record<string, DrizzleAccountHandlers<TContext, TTransaction> | DrizzleCollectionHandlers<TContext, TTransaction>>;
  authorize?: (_: DrizzleSyncAuthorizeInput<TContext>) => void | Promise<void>;
  checkConflict?: (_: DrizzleSyncConflictInput<TContext, TTransaction>) => void | Promise<void>;
};
export type DrizzleAccountHandlers<TContext, TTransaction extends DrizzleLikeTransaction = DrizzleLikeTransaction> = Omit<AccountServerHandlers<TContext>, 'update'> & {
  update?: (_: DrizzleUpdateInput<TContext, TTransaction>) => DrizzleMutationResult | Promise<DrizzleMutationResult>;
};
export type DrizzleCollectionHandlers<TContext, TTransaction extends DrizzleLikeTransaction = DrizzleLikeTransaction> = Omit<CollectionServerHandlers<TContext>, 'create' | 'update' | 'delete'> & {
  create?: (_: DrizzleCreateInput<TContext, TTransaction>) => DrizzleMutationResult | Promise<DrizzleMutationResult>;
  update?: (_: DrizzleUpdateInput<TContext, TTransaction>) => DrizzleMutationResult | Promise<DrizzleMutationResult>;
  delete?: (_: DrizzleDeleteInput<TContext, TTransaction>) => DrizzleMutationResult | Promise<DrizzleMutationResult>;
};
export type DrizzleCreateInput<TContext, TTransaction extends DrizzleLikeTransaction = DrizzleLikeTransaction> = DrizzleMutationInput<TContext, Extract<SyncOp, {
  type: 'create';
}>, TTransaction> & {
  record: JsonRecord;
};
export type DrizzleDeleteInput<TContext, TTransaction extends DrizzleLikeTransaction = DrizzleLikeTransaction> = DrizzleMutationInput<TContext, Extract<SyncOp, {
  type: 'delete';
}>, TTransaction>;
export type DrizzleLikeDatabase<TTransaction extends DrizzleLikeTransaction = DrizzleLikeTransaction> = DrizzleLikeTransaction & {
  transaction?<T>(_: (_: TTransaction) => T | Promise<T>): Promise<T>;
};
export type DrizzleLikeTransaction = {
  insert(_: unknown): {
    values(_: Record<string, unknown>): Promise<unknown> | unknown;
  };
};
export type DrizzleMutationInput<TContext, TOp extends SyncOp, TTransaction extends DrizzleLikeTransaction = DrizzleLikeTransaction> = ServerHandlerContext<TContext> & {
  tx: TTransaction;
  op: TOp;
};
export type DrizzleMutationResult = Omit<ServerMutationResult, 'serverVersion'> & {
  serverVersion?: number;
};
export type DrizzleSyncAuthorizeInput<TContext> = {
  ctx: TContext;
  collection: string;
  op: SyncOp;
};
export type DrizzleSyncConflictInput<TContext, TTransaction extends DrizzleLikeTransaction = DrizzleLikeTransaction> = DrizzleSyncAuthorizeInput<TContext> & {
  tx: TTransaction;
};
export type DrizzleSyncEventConfig<TContext, TTransaction extends DrizzleLikeTransaction = DrizzleLikeTransaction> = {
  write(_: DrizzleSyncEventWriteInput<TContext, TTransaction>): number | Promise<number>;
} | {
  table: unknown;
  nextSeq(_: DrizzleSyncEventWriteInput<TContext, TTransaction>): number | Promise<number>;
  toRow(_: DrizzleSyncEventInput<TContext, TTransaction>): Record<string, unknown>;
};
export type DrizzleSyncEventInput<TContext, TTransaction extends DrizzleLikeTransaction = DrizzleLikeTransaction> = {
  tx: TTransaction;
  ctx: TContext;
  collection: string;
  recordId: string;
  op: SyncOp['type'];
  seq: number;
};
export type DrizzleSyncEventWriteInput<TContext, TTransaction extends DrizzleLikeTransaction = DrizzleLikeTransaction> = Omit<DrizzleSyncEventInput<TContext, TTransaction>, 'seq'>;
export type DrizzleUpdateInput<TContext, TTransaction extends DrizzleLikeTransaction = DrizzleLikeTransaction> = DrizzleMutationInput<TContext, Extract<SyncOp, {
  type: 'update';
}>, TTransaction> & {
  patch: JsonRecord;
};
// #endregion

// #region Functions
export declare function applyOpsWithDrizzle<TContext, TTransaction extends DrizzleLikeTransaction = DrizzleLikeTransaction>(_: ApplyOpsWithDrizzleOptions<TContext, TTransaction>): ServerHandlers<TContext>;
// #endregion