/**
 * Generated by tsnapi — public API snapshot of `valtio-sync/drizzle`
 */
// #region Types
export type ApplyOpsWithDrizzleOptions<TContext> = {
  db: DrizzleLikeDatabase;
  syncEvents: DrizzleSyncEventConfig<TContext>;
  handlers: Record<string, DrizzleAccountHandlers<TContext> | DrizzleCollectionHandlers<TContext>>;
  authorize?: (_: DrizzleSyncAuthorizeInput<TContext>) => void | Promise<void>;
  checkConflict?: (_: DrizzleSyncConflictInput<TContext>) => void | Promise<void>;
};
export type DrizzleAccountHandlers<TContext> = Omit<AccountServerHandlers<TContext>, 'update'> & {
  update?: (_: DrizzleUpdateInput<TContext>) => DrizzleMutationResult | Promise<DrizzleMutationResult>;
};
export type DrizzleCollectionHandlers<TContext> = Omit<CollectionServerHandlers<TContext>, 'create' | 'update' | 'delete'> & {
  create?: (_: DrizzleCreateInput<TContext>) => DrizzleMutationResult | Promise<DrizzleMutationResult>;
  update?: (_: DrizzleUpdateInput<TContext>) => DrizzleMutationResult | Promise<DrizzleMutationResult>;
  delete?: (_: DrizzleDeleteInput<TContext>) => DrizzleMutationResult | Promise<DrizzleMutationResult>;
};
export type DrizzleCreateInput<TContext> = DrizzleMutationInput<TContext, Extract<SyncOp, {
  type: 'create';
}>> & {
  record: JsonRecord;
};
export type DrizzleDeleteInput<TContext> = DrizzleMutationInput<TContext, Extract<SyncOp, {
  type: 'delete';
}>>;
export type DrizzleLikeDatabase = {
  transaction?<T>(_: (_: DrizzleLikeDatabase) => Promise<T>): Promise<T>;
  insert(_: unknown): {
    values(_: Record<string, unknown>): Promise<unknown> | unknown;
  };
};
export type DrizzleMutationInput<TContext, TOp extends SyncOp> = ServerHandlerContext<TContext> & {
  tx: DrizzleLikeDatabase;
  op: TOp;
};
export type DrizzleMutationResult = Omit<ServerMutationResult, 'serverVersion'> & {
  serverVersion?: number;
};
export type DrizzleSyncAuthorizeInput<TContext> = {
  ctx: TContext;
  collection: string;
  op: SyncOp;
};
export type DrizzleSyncConflictInput<TContext> = DrizzleSyncAuthorizeInput<TContext> & {
  tx: DrizzleLikeDatabase;
};
export type DrizzleSyncEventConfig<TContext> = {
  table: unknown;
  nextSeq(_: Omit<DrizzleSyncEventInput<TContext>, 'seq'>): number | Promise<number>;
  toRow(_: DrizzleSyncEventInput<TContext>): Record<string, unknown>;
};
export type DrizzleSyncEventInput<TContext> = {
  tx: DrizzleLikeDatabase;
  ctx: TContext;
  collection: string;
  recordId: string;
  op: SyncOp['type'];
  seq: number;
};
export type DrizzleUpdateInput<TContext> = DrizzleMutationInput<TContext, Extract<SyncOp, {
  type: 'update';
}>> & {
  patch: JsonRecord;
};
// #endregion

// #region Functions
export declare function applyOpsWithDrizzle<TContext>(_: ApplyOpsWithDrizzleOptions<TContext>): ServerHandlers<TContext>;
// #endregion