/**
 * Generated by tsnapi — public API snapshot of `valtio-sync/drizzle`
 */
// #region Types
export type JsonRecord = Record<string, JsonValue>;
export type SyncOp = CreateSyncOp | UpdateSyncOp | DeleteSyncOp;
export type SyncResponse = {
  serverSeq: number;
  accepted: AcceptedSyncOp[];
  rejected: RejectedSyncOp[];
  changes: Record<string, CollectionChanges>;
};
// #endregion

// #region Functions
export declare function applyOpsWithDrizzle(): never;
// #endregion