/**
 * Generated by tsnapi — public API snapshot of `valtio-sync`
 */
// #region Types
export type AcceptedSyncOp = {
  mutationId: string;
  collection: string;
  id: string;
  serverVersion: number;
  record?: JsonRecord;
};
export type CollectionChanges = {
  upserted: Array<{
    id: string;
    serverVersion: number;
    record: JsonRecord;
  }>;
  deleted: Array<{
    id: string;
    serverVersion: number;
  }>;
};
export type CreateSyncOp = {
  mutationId: string;
  collection: string;
  type: 'create';
  id: string;
  value: JsonRecord;
  touched: string[];
};
export type DeleteSyncOp = {
  mutationId: string;
  collection: string;
  type: 'delete';
  id: string;
  baseServerVersion: number | null;
};
export type JsonRecord = Record<string, JsonValue>;
export type JsonValue = string | number | boolean | null | JsonValue[] | {
  [key: string]: JsonValue;
};
export type RejectedSyncOp = {
  mutationId: string;
  collection: string;
  id: string;
  reason: SyncRejectionReason;
  message?: string;
  serverRecord?: JsonRecord;
  serverVersion?: number;
};
export type SyncError = {
  reason: SyncRejectionReason | 'network' | 'auth';
  message?: string;
};
export type SyncOp = CreateSyncOp | UpdateSyncOp | DeleteSyncOp;
export type SyncRejectionReason = 'validation' | 'forbidden' | 'conflict' | 'not_found' | 'server_error';
export type SyncRequest = {
  clientId: string;
  schemaVersion: number;
  lastServerSeq: number | null;
  ops: SyncOp[];
};
export type SyncResponse = {
  serverSeq: number;
  accepted: AcceptedSyncOp[];
  rejected: RejectedSyncOp[];
  changes: Record<string, CollectionChanges>;
};
export type UpdateSyncOp = {
  mutationId: string;
  collection: string;
  type: 'update';
  id: string;
  patch: JsonRecord;
  touched: string[];
  baseServerVersion: number | null;
};
// #endregion

// #region Functions
export declare function isJsonRecord(_: unknown): value is JsonRecord;
export declare function parseSyncRequest(_: unknown): SyncRequest;
export declare function parseSyncResponse(_: unknown): SyncResponse;
// #endregion

// #region Variables
export declare const collectionChangesSchema: z.ZodType<CollectionChanges>;
export declare const jsonRecordSchema: z.ZodType<JsonRecord>;
export declare const jsonValueSchema: z.ZodType<JsonValue>;
export declare const syncOpSchema: z.ZodType<SyncOp>;
export declare const syncRequestSchema: z.ZodType<SyncRequest>;
export declare const syncResponseSchema: z.ZodType<SyncResponse>;
// #endregion

// #region Other
export { ACCOUNT_COLLECTION }
export { ACCOUNT_ID }
export { AccountDefinition }
export { AccountKey }
export { assertJsonRecord }
export { CollectionDefinition }
export { CollectionKey }
export { defineAccount }
export { defineCollection }
export { defineLocalState }
export { FieldMap }
export { FieldSchema }
export { getAccountKey }
export { getCollectionDefinition }
export { getCollectionKeys }
export { getDefaults }
export { infer }
export { InferFields }
export { parseLocalState }
export { parsePatch }
export { parseRecord }
export { SchemaDefinition }
export { SchemaKind }
export { SyncSchema }
// #endregion