/**
 * Generated by tsnapi — public API snapshot of `valtio-sync/schema`
 */
// #region Types
export type AccountDefinition<TFields extends FieldMap = FieldMap> = {
  readonly kind: 'account';
  readonly fields: TFields;
  readonly recordSchema: z.ZodObject<TFields>;
  readonly schema: z.ZodObject<TFields>;
};
export type AccountKey<TSchema extends SyncSchema> = { [K in keyof TSchema]: TSchema[K] extends AccountDefinition ? K : never }[keyof TSchema];
export type CollectionDefinition<TFields extends FieldMap = FieldMap> = {
  readonly kind: 'collection';
  readonly fields: TFields;
  readonly recordSchema: z.ZodObject<TFields>;
  readonly schema: z.ZodObject<TFields>;
};
export type CollectionKey<TSchema extends SyncSchema> = { [K in keyof TSchema]: TSchema[K] extends CollectionDefinition ? K : never }[keyof TSchema];
export type DefinitionOptions<TFields extends FieldMap> = {
  fields: TFields;
  refine?: RecordRefinement<TFields>;
};
export type FieldMap = Record<string, FieldSchema>;
export type FieldSchema = z.ZodType<unknown>;
export type InferFields<TFields extends FieldMap> = { -readonly [K in keyof TFields]: z.output<TFields[K]> };
export type RecordRefinement<TFields extends FieldMap> = Parameters<z.ZodObject<TFields>['superRefine']>[0];
export type SchemaDefinition<TFields extends FieldMap = FieldMap> = AccountDefinition<TFields> | CollectionDefinition<TFields>;
export type SchemaKind = 'account' | 'collection';
export type SyncSchema = Record<string, SchemaDefinition>;
// #endregion

// #region Functions
export declare function assertJsonRecord(_: unknown, _?: string): asserts value is JsonRecord;
export declare function defineAccount<const TFields extends FieldMap>(_: DefinitionOptions<TFields>): AccountDefinition<TFields>;
export declare function defineCollection<const TFields extends FieldMap>(_: DefinitionOptions<TFields>): CollectionDefinition<TFields>;
export declare function defineLocalState<const TFields extends FieldMap>(_: TFields): z.ZodObject<TFields>;
export declare function getAccountKey<TSchema extends SyncSchema>(_: TSchema): AccountKey<TSchema>;
export declare function getCollectionDefinition(_: SyncSchema, _: string): SchemaDefinition | undefined;
export declare function getCollectionKeys<TSchema extends SyncSchema>(_: TSchema): Array<CollectionKey<TSchema>>;
export declare function getDefaults<TFields extends FieldMap>(_: SchemaDefinition<TFields>): InferFields<TFields>;
export declare function parseLocalState<TFields extends FieldMap>(_: TFields, _: unknown): InferFields<TFields>;
export declare function parsePatch<TFields extends FieldMap>(_: SchemaDefinition<TFields>, _: unknown): Partial<InferFields<TFields>>;
export declare function parseRecord<TFields extends FieldMap>(_: SchemaDefinition<TFields>, _: unknown): InferFields<TFields>;
// #endregion

// #region Variables
export declare const ACCOUNT_COLLECTION: string;
export declare const ACCOUNT_ID: string;
// #endregion

// #region Other
export { infer }
// #endregion