/**
 * Generated by tsnapi — public API snapshot of `valtio-sync/server`
 */
// #region Types
export type AcceptedSyncOp = {
  mutationId: string;
  collection: string;
  id: string;
  serverVersion: number;
  record?: JsonRecord;
};
export type AccountDefinition<TFields extends FieldMap = FieldMap> = {
  readonly kind: 'account';
  readonly fields: TFields;
  readonly schema: z.ZodObject<TFields>;
};
export type AccountServerHandlers<TContext> = {
  readChanges?: (_: ServerHandlerContext<TContext> & {
    since: number | null;
  }) => ServerChangesResult | Promise<ServerChangesResult>;
  readSnapshot?: (_: ServerHandlerContext<TContext>) => ServerChangesResult | Promise<ServerChangesResult>;
  update?: (_: ServerHandlerContext<TContext> & {
    op: UpdateSyncOp;
    patch: JsonRecord;
  }) => ServerMutationResult | Promise<ServerMutationResult>;
};
export type CollectionChanges = {
  mode?: CollectionChangesMode;
  upserted: Array<{
    id: string;
    serverVersion: number;
    record: JsonRecord;
  }>;
  deleted: Array<{
    id: string;
    serverVersion: number;
  }>;
};
export type CollectionChangesMode = 'changes' | 'snapshot';
export type CollectionDefinition<TFields extends FieldMap = FieldMap> = {
  readonly kind: 'collection';
  readonly fields: TFields;
  readonly schema: z.ZodObject<TFields>;
};
export type CollectionServerHandlers<TContext> = {
  readChanges?: (_: ServerHandlerContext<TContext> & {
    since: number | null;
  }) => ServerChangesResult | Promise<ServerChangesResult>;
  readSnapshot?: (_: ServerHandlerContext<TContext>) => ServerChangesResult | Promise<ServerChangesResult>;
  create?: (_: ServerHandlerContext<TContext> & {
    op: CreateSyncOp;
    record: JsonRecord;
  }) => ServerMutationResult | Promise<ServerMutationResult>;
  update?: (_: ServerHandlerContext<TContext> & {
    op: UpdateSyncOp;
    patch: JsonRecord;
  }) => ServerMutationResult | Promise<ServerMutationResult>;
  delete?: (_: ServerHandlerContext<TContext> & {
    op: DeleteSyncOp;
  }) => ServerMutationResult | Promise<ServerMutationResult>;
};
export type CreateSyncOp = {
  mutationId: string;
  collection: string;
  type: 'create';
  id: string;
  value: JsonRecord;
  touched: string[];
};
export type DeleteSyncOp = {
  mutationId: string;
  collection: string;
  type: 'delete';
  id: string;
  baseServerVersion: number | null;
};
export type FieldMap = Record<string, FieldSchema>;
export type InferFields<TFields extends FieldMap> = { -readonly [K in keyof TFields]: z.output<TFields[K]> };
export type JsonRecord = Record<string, JsonValue>;
export type JsonValue = string | number | boolean | null | JsonValue[] | {
  [key: string]: JsonValue;
};
export type RejectedSyncOp = {
  mutationId: string;
  collection: string;
  id: string;
  reason: SyncRejectionReason;
  message?: string;
  serverRecord?: JsonRecord;
  serverVersion?: number;
};
export type ServerChangesResult = {
  serverSeq?: number;
  changes: CollectionChanges;
};
export type ServerHandlerContext<TContext> = {
  request: Request;
  ctx: TContext;
};
export type ServerHandlers<TContext> = Record<string, AccountServerHandlers<TContext> | CollectionServerHandlers<TContext>>;
export type ServerMutationResult = {
  serverVersion: number;
  record?: JsonRecord;
};
export type SyncError = {
  reason: SyncRejectionReason | 'network' | 'auth';
  message?: string;
};
export type SyncOp = CreateSyncOp | UpdateSyncOp | DeleteSyncOp;
export type SyncRejectionReason = 'validation' | 'forbidden' | 'conflict' | 'not_found' | 'server_error';
export type SyncRequest = {
  clientId: string;
  schemaVersion: number;
  lastServerSeq: number | null;
  ops: SyncOp[];
};
export type SyncResponse = {
  serverSeq: number;
  accepted: AcceptedSyncOp[];
  rejected: RejectedSyncOp[];
  changes: Record<string, CollectionChanges>;
};
export type SyncSchema = Record<string, SchemaDefinition>;
export type UpdateSyncOp = {
  mutationId: string;
  collection: string;
  type: 'update';
  id: string;
  patch: JsonRecord;
  touched: string[];
  baseServerVersion: number | null;
};
export type ValtioSyncServer = {
  handle(_: Request): Promise<Response>;
};
export type ValtioSyncServerOptions<TSchema extends SyncSchema, TContext> = {
  schema: TSchema;
  handlers: ServerHandlers<TContext>;
  getContext?: (_: Request) => TContext | Promise<TContext>;
};
// #endregion

// #region Classes
export declare class SyncRejection extends Error {
  reason: SyncRejectionReason;
  serverRecord?: JsonRecord;
  serverVersion?: number;
  constructor(_: SyncRejectionReason, _?: string, _?: {
    serverRecord?: JsonRecord;
    serverVersion?: number;
  });
}
// #endregion

// #region Functions
export declare function parseSyncRequest(_: unknown): SyncRequest;
export declare function parseSyncResponse(_: unknown): SyncResponse;
export declare function rejectSync(_: SyncRejectionReason, _?: string, _?: {
  serverRecord?: JsonRecord;
  serverVersion?: number;
}): never;
export declare function valtioSync<const TSchema extends SyncSchema, TContext = undefined>(_: ValtioSyncServerOptions<TSchema, TContext>): ValtioSyncServer;
// #endregion

// #region Other
export { infer }
// #endregion